name: 🌸 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: 🌸 Build
    runs-on: macos-latest

    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
          
      - name: ☕️ set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'zulu'
            cache: gradle

      - name: 🧱 Install Dependencies
        run: |
          npm install
          cd ios && pod install

      - name: 🧬 Build
        env:
          scheme: ${{ 'default' }}
        run: |
          make all

      - name: ⬆️ Upload Build Artifact
        env:
          scheme: ${{ 'default' }}
        run: |
          buildtime=$(date '+%Y%m%d.%H%M')
          curl --location "https://drive.endemy.me/od_bot/build/iPlay/$buildtime/iPlay.ipa" \
            --data-binary "@$PWD/Build/iPlay.ipa" \
            --header "Authorization: ${{ secrets.CLIENT_ID }}"\
            --header "Content-Type: application/zip" \
            --progress-bar | tee /dev/null
          curl --location "https://drive.endemy.me/od_bot/build/iPlay/$buildtime/iPlay.apk" \
            --data-binary "@$PWD/Build/iPlay.apk" \
            --header "Authorization: ${{ secrets.CLIENT_ID }}"\
            --header "Content-Type: application/zip" \
            --progress-bar | tee /dev/null
          pip3 install requests
          ./tools/upload.py --url "https://drive.endemy.me/od_bot/build/iPlay/$buildtime/iPlay.dSYMs.zip" \
            --file "$PWD/Build/iPlay.dSYMs.zip" \
            --token "${{ secrets.CLIENT_ID }}"